name: "YAML Read"
description: "This action reads a YAML configuration files, with support to variable interpolation"
author: "pietrobolcato"
branding:
  icon: box
  color: blue
inputs:
  config:
    description: "Config file name"
    required: true
    default: ""
runs:
  using: "node16"
  main: "action_read_yaml/index.js"
