name: "YAML Read"
description: "This is a NodeJS action to read YAML configuration files."
inputs:
  config:
    description: "Config file name"
    required: true
    default: ""
runs:
  using: "node16"
  main: "action_read_yaml/index.js"
