name: "Read YAML"
description: "This action reads a YAML configuration files, with support for variable interpolation."
author: "CrisisTextLine"
branding:
  icon: box
  color: blue
inputs:
  config:
    description: "Config file name"
    required: true
    default: ""
  key-path-pattern:
    description: "Key path to filter out in the yaml file"
    required: false
    default: ""
  env-var-prefix:
    description: "Prefix that will be added as the prefix to the environment variables output"
    required: false
    default: ""
runs:
  using: "node20"
  main: "action_read_yaml/index.js"
