name: helpers-read-yaml

on:
  workflow_call:
    inputs:
      file_name:
        required: true
        type: string
    outputs:
      # infrastructure settings
      location:
        description: "Location"
        value: ${{ jobs.read-yaml.outputs.location }}
      namespace:
        description: "Prefix for module names"
        value: ${{ jobs.read-yaml.outputs.namespace }}
      environment:
        description: "Enviroment of the AML workspace"
        value: ${{ jobs.read-yaml.outputs.environment }}
      postfix:
        description: "Postfix for module names"
        value: ${{ jobs.read-yaml.outputs.postfix }}
      enable_aml_compute_instance:
        description: "Boolean to enable or disable AML compute instance"
        value: ${{ jobs.read-yaml.outputs.enable_aml_compute_instance }}
      virtual_machine_size:
        description: "The size of the VM to create"
        value: ${{ jobs.read-yaml.outputs.virtual_machine_size }}
      ssh_access_ad_group_name:
        description: The name of the active directory group that will have SSH access to the AML compute instance
        value: ${{ jobs.read-yaml.outputs.ssh_access_ad_group_name }}

      # infrastructure naming settings
      resource_group_name:
        description: "Name of the resource group resource"
        value: ${{ jobs.read-yaml.outputs.resource_group_name }}
      aml_workspace_name:
        description: "Name of the machine learning workspace resource"
        value: ${{ jobs.read-yaml.outputs.aml_workspace_name }}
      application_insights_name:
        description: "Name of the application insights resource"
        value: ${{ jobs.read-yaml.outputs.application_insights_name }}
      key_vault_name:
        description: "Name of the key vault resource"
        value: ${{ jobs.read-yaml.outputs.key_vault_name }}
      container_registry_name:
        description: "Name of the container registry resource"
        value: ${{ jobs.read-yaml.outputs.container_registry_name }}
      storage_account_name:
        description: "Name of the storage account resource"
        value: ${{ jobs.read-yaml.outputs.storage_account_name }}

      # terraform settings
      terraform_version:
        description: "Terraform version"
        value: ${{ jobs.read-yaml.outputs.terraform_version }}
      terraform_workingdir:
        description: "Terraform State working directory"
        value: ${{ jobs.read-yaml.outputs.terraform_workingdir }}

      # terraform state settings
      terraform_st_location:
        description: "Terraform State location"
        value: ${{ jobs.read-yaml.outputs.terraform_st_location }}
      terraform_st_resource_group:
        description: "Terraform State Resource Group"
        value: ${{ jobs.read-yaml.outputs.terraform_st_resource_group }}
      terraform_st_storage_account:
        description: "Terraform State Storage Account"
        value: ${{ jobs.read-yaml.outputs.terraform_st_storage_account }}
      terraform_st_container_name:
        description: "Terraform State Container name"
        value: ${{ jobs.read-yaml.outputs.terraform_st_container_name }}
      terraform_st_key:
        description: "Terraform State Key"
        value: ${{ jobs.read-yaml.outputs.terraform_st_key }}

      # github action read sanity check
      gha_sanity_check:
        description: "Sanity check to make sure the YAML file is read correctly"
        value: ${{ jobs.read-yaml.outputs.gha_sanity_check }}
jobs:
  read-yaml:
    runs-on: ubuntu-latest
    outputs:
      # infrastructure settings
      location: ${{  steps.read_action_js.outputs.location }}
      namespace: ${{  steps.read_action_js.outputs.namespace }}
      environment: ${{  steps.read_action_js.outputs.environment }}
      postfix: ${{  steps.read_action_js.outputs.postfix }}
      enable_aml_compute_instance: ${{  steps.read_action_js.outputs.enable_aml_compute_instance }}
      virtual_machine_size: ${{  steps.read_action_js.outputs.virtual_machine_size }}
      ssh_access_ad_group_name: ${{  steps.read_action_js.outputs.ssh_access_ad_group_name }}

      # infrastructure naming settings
      resource_group_name: ${{  steps.read_action_js.outputs.resource_group_name }}
      aml_workspace_name: ${{  steps.read_action_js.outputs.aml_workspace_name }}
      application_insights_name: ${{  steps.read_action_js.outputs.application_insights_name }}
      key_vault_name: ${{  steps.read_action_js.outputs.key_vault_name }}
      container_registry_name: ${{  steps.read_action_js.outputs.container_registry_name }}
      storage_account_name: ${{  steps.read_action_js.outputs.storage_account_name }}

      # terraform settings
      terraform_version: ${{  steps.read_action_js.outputs.terraform_version }}
      terraform_workingdir: ${{  steps.read_action_js.outputs.terraform_workingdir }}
      terraform_st_location: ${{  steps.read_action_js.outputs.terraform_st_location }}
      terraform_st_resource_group: ${{  steps.read_action_js.outputs.terraform_st_resource_group }}
      terraform_st_storage_account: ${{  steps.read_action_js.outputs.terraform_st_storage_account }}
      terraform_st_container_name: ${{  steps.read_action_js.outputs.terraform_st_container_name }}
      terraform_st_key: ${{  steps.read_action_js.outputs.terraform_st_key }}

      # github action read sanity check
      gha_sanity_check: ${{  steps.read_action_js.outputs.gha_sanity_check }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: read-yaml-file
        uses: ./.github/workflows/helpers-read-yaml-action
        id: read_action_js
        with:
          config: ${{ github.workspace }}/${{ inputs.file_name }}
      - name: post-read-sanity-check
        run: echo sanity_check=${{  steps.read_action_js.outputs.gha_sanity_check }}
